### ISSUE TITLE
Running rMATs on a large number of files

### ISSUE THREAD

**Issue by carynhale** [Xinglab/rmats-turbo#139] opened 2021-08-04 16:46 UTC
Hello-
I'm wondering if you know if there's an upper limit to the number of input files that can be analyzed by rMATs?  I'm trying to analysis a very large number of files (~1000 samples per condition), and I'm getting some errors that I can't seem to solve.  I know that my rMATs build is good, as I've tested smaller numbers of the same .rmats files (50, 100, 200 samples per condition) without issue.

We successfully pre-processed all the files, so we're trying to run the --task post, and we consistently get this error:

FileNotFoundError: [Errno 2] No such file or directory: './tmp/JC_A5SS/rMATS_result_P-V.txt'
paste: ./tmp/JC_A5SS/rMATS_result_FDR.txt: No such file or directory
Traceback (most recent call last):
  File "/path/rMATS_P/FDR.py", line 45, in <module>
ifile=open(sys.argv[1]);title=ifile.readline();

When I look in the tmp/ folder, these files:
rMATS_result_ID.txt  
rMATS_result_I-L.txt  
rMATS_result_INP.txt  
rMATS_result_.txt

are all there, but there is no P-V file like there is with the smaller batches.  I tried running the FDR.py script separately and got the same error.  It looks like all of the counting is going well, but not the statistics portion of the script.

I'm wondering if you have any idea of what is causing this error, and what I could do to try to fix it, or if you have any suggestions for ways to get the statistics for large numbers of input files.

Thanks!

**Comment by EricKutschera** [comment] 2021-08-04 18:04
The error message says that there is no `tmp/JC_A5SS/rMATS_result_P-V.txt` which indicates that the statistical model (rMATS_exe) failed and then FDR.py failed because it needs the output from rMATS_exe

In the directory given as `--od` there should be a file called JC.raw.input.A5SS.txt. The command that failed would look something like `rMATS_C/rMATS_exe -i od/JC.raw.input.A5SS.txt -t 1 -o tmp/JC_A5SS/rMATS_result_P-V.txt -c 0.0001`. You could try running that command yourself to see if you get any useful error message. The error message wouldn't have been show by rmats.py since it ignores the output from rMATS_exe because it is very verbose: https://github.com/Xinglab/rmats-turbo/blob/v4.1.1/rmats.py#L415

There was an issue in v4.1.0 where a large number of events would cause rMATS_exe to run out of memory. That issue has been fixed in v4.1.1. If you are using v4.1.0 and can't upgrade to v4.1.1, here is a thread with a suggestion about working around that issue: https://github.com/Xinglab/rmats-turbo/issues/91#issuecomment-784212706

**Comment by carynhale** [comment] 2021-08-05 15:38
Thanks for the advice!  When I run this in the folder of the run that didn't work, I get the following error:

number of thread=1; input file=JC.raw.input.A5SS.txt; output folder=tmp/JC_A5SS/rMATS_result_P-V.txt; cutoff=0.0001;
An error occured. The length of the pair of vector should be equal. Sample Id: 285
Size of vector: 3742, 1, 760, 760
Exiting 

The same command in another folder with less input files seems to run just fine.  Could this be something with one of the files?

**Comment by EricKutschera** [comment] 2021-08-05 18:35
I was able to reproduce a similar error message by running against a count file with a large number of samples. rMATS_C has some hardcoded constants: https://github.com/Xinglab/rmats-turbo/blob/v4.1.1/rMATS_C/include/global.h#L17
This one seems to be causing the error `COLUMN_LEN: 8192`. There is also `MAX_LINE: 10240` but it looks like that is just the initial amount of space to allocate for a line and more space is allocated as needed

Here's the code that uses COLUMN_LEN to split the line into fixed sized arrays: https://github.com/Xinglab/rmats-turbo/blob/v4.1.1/rMATS_C/src/util.c#L199

The columns in the file are comma separated lists of counts. There will be `sample_num - 1` commas and then if all of the counts are single digit there will be `sample_num` additional characters for about `2*sample_num` characters. I think if you have `(sample_num >= 8192/2 = 4096)` then there will be an error. If all of the counts are 2 digits then the error would start at `(sample_num >= 8192/3 = 2730)` and for 3 digits it would start at `(sample_num >= 8192/4 = 2048)`

In your case it looks like you have 3742 samples in the first group and 760 samples in the second group. It looks like the error only happens for the skipping counts of sample 1 and my guess is that there were a lot of 2 or 3 digit counts in that column

If you can build rmats yourself from the source code then I think you can work around this error by changing the value of `COLUMN_LEN` to maybe 81920. Ideally the code could be re-written to not require COLUMN_LEN

**Comment by carynhale** [comment] 2021-08-05 18:57
Okay, so this is a weird thing.  There shouldn't be 3742 samples in that group, it's only 1877.  I just double-checked the input file and yeah, there's 1877 files in there (I grepped "," and there are 1875).  Could it be doubling up the samples somewhere upstream?

**Comment by EricKutschera** [comment] 2021-08-05 19:24
The number reported in the error message comes after processing the array after there was a memory error. Since the array was not large enough to handle the string for that column, I think it overflowed into the space allocated for the next column. Even though the error says `Size of vector: 3742, 1, 760, 760` those numbers could have been impacted by the corrupted memory

I think the `Sample Id: 285` from the error message might be correct. Can you extract the line from JC.raw.input.A5SS.txt that starts with 285? I think that line should have the real number of samples. If one of the columns on that line has at least 8192 characters then I think that explains the error

**Comment by carynhale** [comment] 2021-08-05 19:55
Yep, you're right!  That column has 8233 characters and 1875 commas!  I guess we've found the problem at least.  We'll look into changing the source code, but we also probably don't need to run every single one of the files through at the same time, now that we know that we can hit a limit.

**Closed** 2021-11-19 17:25 UTC
